"""Update foreign keys in Item model

Revision ID: e9d30a133fdf
Revises: ce1fe685a320
Create Date: 2025-01-29 01:30:12.083440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d30a133fdf'
down_revision = 'ce1fe685a320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('itemCategory_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_items_category_id_item_categories', type_='foreignkey')
        batch_op.drop_constraint('fk_items_seller_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_items_itemCategory_id_item_categories'), 'item_categories', ['itemCategory_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_items_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('category_id')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_items_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_items_itemCategory_id_item_categories'), type_='foreignkey')
        batch_op.create_foreign_key('fk_items_seller_id_users', 'users', ['seller_id'], ['id'])
        batch_op.create_foreign_key('fk_items_category_id_item_categories', 'item_categories', ['category_id'], ['id'])
        batch_op.drop_column('itemCategory_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
